### ISSUE TITLE
Philips Hue scenes run into errors while syncing

### ISSUE THREAD

**Issue by vreesie18** [DewGew/DZGA-Flask#100]
As of this morning my Philips Hue scenes coming from Domoticz run into errors. For example domoticz idx 2076 in the log below is one of my scenes. I am pretty sure it worked yesterday.

dzga-flask    | https://homegraph.googleapis.com:443 "POST /v1/devices:requestSync HTTP/1.1" 200 None
dzga-flask    | Device state reported {
dzga-flask    |   "agentUserId": "admin"
dzga-flask    | }
dzga-flask    | request:
dzga-flask    | {
dzga-flask    |   "inputs": [
dzga-flask    |     {
dzga-flask    |       "intent": "action.devices.QUERY",
dzga-flask    |       "payload": {
dzga-flask    |         "devices": [
dzga-flask    |           {
dzga-flask    |             "customData": {
dzga-flask    |               "check_state": true,
dzga-flask    |               "domain": "ColorSwitch",
dzga-flask    |               "dzTags": false,
dzga-flask    |               "idx": "2076",
dzga-flask    |               "protected": false
dzga-flask    |             },
dzga-flask    |             "id": "ColorSwitch_2076"
dzga-flask    |           }
dzga-flask    |         ]
dzga-flask    |       }
dzga-flask    |     }
dzga-flask    |   ],
dzga-flask    |   "requestId": "12699071185056915168"
dzga-flask    | }
dzga-flask    | Starting new HTTP connection (1): 192.168.1.10:8181
dzga-flask    | http://192.168.1.10:8181 "GET /json.htm?type=command&param=getdevices&rid=2076 HTTP/1.1" 200 686
dzga-flask    | Traceback (most recent call last):
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2213, in __call__
dzga-flask    |     return self.wsgi_app(environ, start_response)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
dzga-flask    |     return self.app(environ, start_response)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2193, in wsgi_app
dzga-flask    |     response = self.handle_exception(e)
dzga-flask    |                ^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
dzga-flask    |     response = self.full_dispatch_request()
dzga-flask    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
dzga-flask    |     rv = self.handle_user_exception(e)
dzga-flask    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
dzga-flask    |     rv = self.dispatch_request()
dzga-flask    |          ^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
dzga-flask    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/smarthome.py", line 304, in fulfillment
dzga-flask    |     query = smarthome.query(user_id, i['payload'], requestId)
dzga-flask    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/modules/intents.py", line 59, in query
dzga-flask    |     devices[device['id']] = trait.query(custom_data, attr, user_id)
dzga-flask    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/modules/trait.py", line 51, in query
dzga-flask    |     color_rgb = json.loads(state['Color'])
dzga-flask    |                            ^^^^^^^^^^^^^^^
dzga-flask    | KeyError: 'Color'
dzga-flask    | Starting new HTTP connection (1): 192.168.1.10:8181
dzga-flask    | Starting new HTTP connection (1): 192.168.1.10:8181
dzga-flask    | http://192.168.1.10:8181 "GET /json.htm?type=command&param=getusers HTTP/1.1" 200 42
dzga-flask    | http://192.168.1.10:8181 "GET /json.htm?type=command&param=getversion HTTP/1.1" 200 209
dzga-flask    | request:
dzga-flask    | {
dzga-flask    |   "inputs": [
dzga-flask    |     {
dzga-flask    |       "intent": "action.devices.QUERY",
dzga-flask    |       "payload": {
dzga-flask    |         "devices": [
dzga-flask    |           {
dzga-flask    |             "customData": {
dzga-flask    |               "check_state": true,
dzga-flask    |               "domain": "ColorSwitch",
dzga-flask    |               "dzTags": false,
dzga-flask    |               "idx": "2076",
dzga-flask    |               "protected": false
dzga-flask    |             },
dzga-flask    |             "id": "ColorSwitch_2076"
dzga-flask    |           }
dzga-flask    |         ]
dzga-flask    |       }
dzga-flask    |     }
dzga-flask    |   ],
dzga-flask    |   "requestId": "15730516766078580663"
dzga-flask    | }
dzga-flask    | Starting new HTTP connection (1): 192.168.1.10:8181
dzga-flask    | http://192.168.1.10:8181 "GET /json.htm?type=command&param=getdevices&rid=2076 HTTP/1.1" 200 687
dzga-flask    | Traceback (most recent call last):
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2213, in __call__
dzga-flask    |     return self.wsgi_app(environ, start_response)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
dzga-flask    |     return self.app(environ, start_response)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2193, in wsgi_app
dzga-flask    |     response = self.handle_exception(e)
dzga-flask    |                ^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
dzga-flask    |     response = self.full_dispatch_request()
dzga-flask    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
dzga-flask    |     rv = self.handle_user_exception(e)
dzga-flask    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
dzga-flask    |     rv = self.dispatch_request()
dzga-flask    |          ^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
dzga-flask    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/smarthome.py", line 304, in fulfillment
dzga-flask    |     query = smarthome.query(user_id, i['payload'], requestId)
dzga-flask    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/modules/intents.py", line 59, in query
dzga-flask    |     devices[device['id']] = trait.query(custom_data, attr, user_id)
dzga-flask    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/modules/trait.py", line 51, in query
dzga-flask    |     color_rgb = json.loads(state['Color'])
dzga-flask    |                            ^^^^^^^^^^^^^^^
dzga-flask    | KeyError: 'Color'
dzga-flask    | request:
dzga-flask    | {
dzga-flask    |   "inputs": [
dzga-flask    |     {
dzga-flask    |       "intent": "action.devices.QUERY",
dzga-flask    |       "payload": {
dzga-flask    |         "devices": [
dzga-flask    |           {
dzga-flask    |             "customData": {
dzga-flask    |               "check_state": true,
dzga-flask    |               "domain": "ColorSwitch",
dzga-flask    |               "dzTags": false,
dzga-flask    |               "idx": "2076",
dzga-flask    |               "protected": false
dzga-flask    |             },
dzga-flask    |             "id": "ColorSwitch_2076"
dzga-flask    |           }
dzga-flask    |         ]
dzga-flask    |       }
dzga-flask    |     }
dzga-flask    |   ],
dzga-flask    |   "requestId": "6879707336608574593"
dzga-flask    | }
dzga-flask    | Starting new HTTP connection (1): 192.168.1.10:8181
dzga-flask    | http://192.168.1.10:8181 "GET /json.htm?type=command&param=getdevices&rid=2076 HTTP/1.1" 200 686
dzga-flask    | Traceback (most recent call last):
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2213, in __call__
dzga-flask    |     return self.wsgi_app(environ, start_response)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
dzga-flask    |     return self.app(environ, start_response)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2193, in wsgi_app
dzga-flask    |     response = self.handle_exception(e)
dzga-flask    |                ^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
dzga-flask    |     response = self.full_dispatch_request()
dzga-flask    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
dzga-flask    |     rv = self.handle_user_exception(e)
dzga-flask    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
dzga-flask    |     rv = self.dispatch_request()
dzga-flask    |          ^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
dzga-flask    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
dzga-flask    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/smarthome.py", line 304, in fulfillment
dzga-flask    |     query = smarthome.query(user_id, i['payload'], requestId)
dzga-flask    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/modules/intents.py", line 59, in query
dzga-flask    |     devices[device['id']] = trait.query(custom_data, attr, user_id)
dzga-flask    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dzga-flask    |   File "/modules/trait.py", line 51, in query
dzga-flask    |     color_rgb = json.loads(state['Color'])
dzga-flask    |                            ^^^^^^^^^^^^^^^
dzga-flask    | KeyError: 'Color'
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dzga-flask ... done

**Comment by DewGew** [comment]
What kind of device is it in domoticz? What does the output show?

Https://ipadress:8080/json.htm?type=command&param=getdevices&rid=2076

**Comment by vreesie18** [comment]
{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Off",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 12,
			"HardwareName" : "hue",
			"HardwareType" : "Philips Hue Bridge",
			"HardwareTypeVal" : 38,
			"HaveDimmer" : true,
			"HaveGroupCmd" : false,
			"HaveTimeout" : false,
			"ID" : "00000810",
			"Image" : "Push",
			"InternalState" : "Off",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-02-10 09:59:25",
			"Level" : 0,
			"LevelInt" : 0,
			"MaxDimLevel" : 100,
			"Name" : "Scene Normal",
			"Notifications" : "false",
			"PlanID" : "11",
			"PlanIDs" : 
			[
				11,
				25
			],
			"Protected" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "RGBW",
			"SwitchType" : "Push On Button",
			"SwitchTypeVal" : 9,
			"Timers" : "false",
			"Type" : "Color Switch",
			"TypeImg" : "push",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "2076"
		},

**Comment by DewGew** [comment]
Its added like a color switch type in domoticz. Is it automaticly added?

**Comment by vreesie18** [comment]
Yes, from type Hue in the devices menu in Domoticz.

**Comment by DewGew** [comment]
But can you set colors? If not i should be a normal light/switch.

**Comment by vreesie18** [comment]
Yes, you can set colors in Domoticz but nothing changes. But I think you are right, domoticz should not add a hue scene as a color device but that should have been a switch, sub-type push-on. For now as a work-a-round, I add a dummy push button in domoticz, add it to the dzga room and handle the event in domoticz script.

**Comment by DewGew** [comment]
And in the json output there is no color key.
