### ISSUE TITLE
Issue controling groups by voice

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#107]
I have an issue that started with build 24.4 and continues with subsequent versions. Version 24.3 is the one that worked correctly. When I attempt to turn on or off a group or all lights, only a few lights respond as expected. It seems that when the system encounters a light that is already in the correct state, it stops attempting to change the state of the other lights in the group. In the logs (when running manually), I can see the commands being sent to Domoticz, but Domoticz doesn't seem to receive them. In version 24.3, I observe similar behavior, but the difference is that Domoticz does receive the command. I have no clue how I can make this visible for you to debug.

**Comment by DewGew** [comment]
Do you rin dzga manually? For debugging its more logs when running manually

**Comment by Xenomes** [comment]
Yes i used
```
source env/bin/activate
python3 smarthome.py
```
There are no error...

**Comment by DewGew** [comment]
I can you check if any device is already in state. Maybe thats the issue. I added this function after V24.3

**Comment by Xenomes** [comment]
Yes there are devices in the off state. For example, when i call to turn all lights off, the 'shed lamp' is always off there are a lot more that are already off, I have 34 devices as Light (17 OnOff, 15 ColorSwitch and 2 dimmer). These devices are organized into three groups: living room, kitchen, and outside.

**Comment by Xenomes** [comment]
```git
commit 1e416a25d8da0bafd28f398b7228ca26f3bc3496
Author: DewGew <pierlar@hotmail.com>
Date:   Wed Jan 31 09:45:20 2024 +0100

    Add energystorage trait to check batterylevel

commit cfa5d57eec035d6aec27aa6c17c78d67a73eec9c
Author: DewGew <pierlar@hotmail.com>
Date:   Wed Jan 31 08:56:37 2024 +0100

    Add report low battery level

commit 5f0e860d9776be879c8517ee383a47a5dcb40b9c
Author: DewGew <pierlar@hotmail.com>
Date:   Wed Jan 31 08:46:12 2024 +0100

    Add BatteryLevel

commit 47926959555e124e6e9d298e73fb99dc33b37711
Author: DewGew <pierlar@hotmail.com>
Date:   Wed Jan 31 08:42:00 2024 +0100

    Add Batterylevel on dashboard devices

commit 71c353497be3607652557aced80c3a30685043fd (tag: V24,3)
Author: DewGew <pierlar@hotmail.com>
Date:   Tue Jan 30 18:47:20 2024 +0100

    Create stale.yml
```
I did some testing Commit 71c353497be3607652557aced80c3a30685043fd works in my situation and 1e416a25d8da0bafd28f398b7228ca26f3bc3496 gives the problem, the commits in between i could not test the wife got home, lights on / off / on is not 'partner's approval factor' 😅
