### ISSUE TITLE
Config yaml file not read

### ISSUE THREAD

**Issue by RunnicFusion** [DewGew/DZGA-Flask#108]
Currently installed a fresh Dzga flask installation trough Docker on my Synology nas.
Flask application will start but contains default credentials and settings.

Was using Dzga and looks like, correct me if I'm wrong, most of the config.yaml file is exactly the same as before.
Created 3 virtual folders, /config /instance and /uploads.

When logging into Dzga the default settings are loaded instead of my config values. Same for the Google home key json file. Logs are telling me key is not present.

Did I do something wrong?
Wiki isn't telling very much about what steps to take. Got my info from docker files in this repo.

**Comment by DewGew** [comment]
You set all settings in the userinterface

**Comment by RunnicFusion** [comment]
Why is the docker compose file saying I need to use the config.yaml? What about specific settings about devices?
Are those yaml and js files not used?

Also wiki is missing a bit of information about this topic:
- what folders to create
- what ports to forward (found already)
- default login flow
- how to config settings

**Comment by DewGew** [comment]
Did you follow this https://github.com/DewGew/DZGA-Flask/wiki/1.-Installation#usage-with-docker-compose

No need to create folders composer do that for you at /opt/DZGA-Flask

**Comment by RunnicFusion** [comment]
Yes I did. 

What is the use of config.yaml when credentials are not loaded from that file?

**Comment by DewGew** [comment]
For DZGA-Flask there is no config.yaml
