### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by atmfrenki** [DewGew/DZGA-Flask#110]
Hi all,
I have a Freshly installed version 24.9 on a new Pi with the latest Raspbian OS

DZGA-Flask looks fine, the sync with domoticz works fine. (all devices from domoticz are visable)
I setup a new GoogleAction (I'm migrating from the old DZGA that worked perfectly) and imported a new key.json file.

When adding the new [test]actionname in Google Home app, I get as result: 400 Bad Request

Also when I externaly and internal test the URL's in a browser ( https://[my url]/smarthome or https://[my url]/oauth or https://[my url]/token) I get the same result visible in the browser.

The URL for Domoticz interface is resolvable on 443 from external and internal, no problem there.
Checked my firewall for traffic deny's but all requests are coming in.

What am I missing?

**Comment by atmfrenki** [comment]
Update, through ngrok it works, no error.
Only need to find out how ngrok keeps running after a reboot or the terminal windows closes.

Thanks for all the effort!!

**Comment by DewGew** [comment]
Next, connect your ngrok agent to your ngrok account. If you haven't already, [sign up for an ngrok account](https://dashboard.ngrok.com/). Copy your [ngrok authtoken](https://dashboard.ngrok.com/get-started/your-authtoken) from your ngrok dashboard then run:
ngrok config add-authtoken <TOKEN>

if you want to keep the same URL each time you use ngrok, [create a static domain on your dashboard](https://dashboard.ngrok.com/cloud-edge/domains) and then use the --domain flag to ask the ngrok agent to use it. First, stop ngrok with Ctrl+C and then run ngrok again:
ngrok http 8181 --domain <static.url>.ngrok-free.app




Run ngrok as service:
https://ngrok.com/docs/agent/#background-service

**Comment by atmfrenki** [comment]
Thanks, i´ve got it as a service now. Works!!
