### ISSUE TITLE
Does this allow me to control Domoticz via Google Assistent?

### ISSUE THREAD

**Issue by vespino** [DewGew/DZGA-Flask#117]
Just a simple question as it's not quite clear what this project does. Recently the homebridge plugin I've been using for years (https://github.com/oznu/homebridge-gsh) got archived so I guess it's a matter of time before it doesn't work any more. That is why I'm looking for a replacement.

**Comment by d-EScape** [comment]
Yes it does

**Comment by vespino** [comment]
Ah nice. I have gotten round to diving into it yet, but is there a step by step tutorial somewhere? Maybe a video?

**Comment by TheReptile** [comment]
There's a wiki which has a guide to install: https://github.com/DewGew/DZGA-Flask/wiki

**Comment by vespino** [comment]
Installing is not the problem, I don’t quite understand the Google part.

**Comment by ayasystems** [comment]
> Installing is not the problem, I don’t quite understand the Google part.

Just follow the wiki, if you have a problem ask 

the wiki is very clear and has all links to google cloud

https://github.com/DewGew/DZGA-Flask/wiki/2.-Setup-Actions-on-Google

**Comment by vespino** [comment]
When watching a few tutorials on Home Assistant with Google Assistant I found I have to add the project to Google Home which I don't see mentioned anywhere in the wiki, correct? When I do this, I'm told my project is connected, but an error occurs saying "something went wrong, please try again".

Edit: after waiting a while and trying it again the process completed without errors and now shows a few items. I will try and remove homebridge from the equation and see what happens.

**Comment by ayasystems** [comment]
Check the old wiki, seems not be updated in the new 

https://github.com/DewGew/Domoticz-Google-Assistant/wiki/4.-Connect-smart-home-devices-to-your-Google-Home-device

**Comment by vespino** [comment]
@ayasystems is this the only thing missing from the wiki? Do I need to set devices for my Domoticz user for example or are all devices synced by default? Think I'm getting closer, that's a good thing.

**Comment by ayasystems** [comment]
if you are ussing a specific user you need add these devices to this user and the same with the plans

If the user and plans are correct you can see the devices into dashboard of DZGA

**Comment by vespino** [comment]
Strang thing: without assigning the devices they do show up in DZGA. Meanwhile adding the devices to Google Home stopped working.

**Comment by ayasystems** [comment]
I'm not sure but could be that the user has all devices if you dont add devices to allow column

**Comment by vespino** [comment]
Think I have it working now, everything but dimmable lights that is. Progress!
