### ISSUE TITLE
Wrong command for installation on wiki page

### ISSUE THREAD

**Issue by perkovich** [DewGew/DZGA-Flask#31]
Sorry, not very familiar with the wiki on Github. Can I edit the pages directly? 

[The installation page](https://github.com/DewGew/DZGA-Flask/wiki/1.-Installation) in the wiki has the command for installation wrong. Running it gives a 404. 

The command says:
https://raw.githubusercontent.com/DewGew/dzga-installer/development/dzga-flask-install.sh

But should probably be (as it says on the [first page](https://github.com/dewgew/dzga-flask)):
bash <(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/DZGA-Flask-install.sh)

**Comment by DewGew** [comment]
Thanks. I have updated wiki
