### ISSUE TITLE
Saving Configuration with Docker

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#34]
Hi,

First, congratulations on the update to the new dzga-flask!

I am using dzga-flask in a Docker container. When running, the following files are created on my host in the config directory: admin_devices.json and smarthome.log. However, I am missing the file where all configurations are stored, so updating the Docker will erase the settings.

Greetings,
Xenomes.

**Comment by DewGew** [comment]
Settings i saved in a sqlite file in instance folder. Maybe its better to save this file in config folder?
Or creata a volume for instance folder?
If you update docker the instance folder will be deleted?

**Comment by Xenomes** [comment]
I will test the volume for the 'instance' folder.

**Comment by Xenomes** [comment]
The 'instance' option is functioning properly. You can update the docker-compose.yaml and Dockerfile to include the 'instance'.
