### ISSUE TITLE
Unable to activate SSL

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#39]
Hi, I just updated to the latest version 23.8. I'm attempting to enable SSL using the same certificate and key that I successfully used with the previous version (DZGA), but it doesn't seem to be working for me. The message I'm encountering after the boot is:
```
2023-11-17 20:38:55 Smarthome server has started.
2023-11-17 20:38:55 Running without ssl
```

**Comment by DewGew** [comment]
#41 try without checking for ssl files.

**Comment by DewGew** [comment]
From @Xenomes On a clean install, running in the Python venv, SSL works. Running it in Docker (Dockerfile) results in an error.

**Comment by DewGew** [comment]
Maybe need to add a volume for ssl cert and keys in dockerfile  or put the cert and keys in config folder?

**Comment by Xenomes** [comment]
Yes, that is a good idea to put them there. Then the issue is resolved; I am testing it right now.

Update:
Putting the files in the config and changing the path to /config/, the SSL is running in the Docker. Also the ${USER}, ${HOME} or ~ is not working in the docker yaml file. When hard coding the path to /home/pi/DZGA-Flask the volumes where working.

**Comment by DewGew** [comment]
Are running with docker compose?
${USER} works for me with composer

**Comment by Xenomes** [comment]
Yes, I use Docker Compose.
`sudo docker-compose -f dzga-compose.yaml up -d`
The Docker starts, but the volumes weren't used.

**Comment by Xenomes** [comment]
Issue with SSL was fixed, volumes is a docker or Ubuntu issue,
