### ISSUE TITLE
BlindsPercentage device type is missing

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#47]
Hi,
BlindsPercentage device type is missing.
![afbeelding](https://github.com/DewGew/DZGA-Flask/assets/11648297/33f30195-ed83-485c-bea9-be9adce1218b)

**Comment by DewGew** [comment]
Maybe you already have this device under switches. I see i forgot to remove BlindsPercentage from other devices so it will be a dubble🤔

**Comment by Xenomes** [comment]
You are correct, BlindsPercentage is double, missed that.

**Comment by DewGew** [comment]
Fixed in latest
