### ISSUE TITLE
Asking Google to turn on or off multiple devices doesn't work.

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#54]
When I ask Google to turn off one light, it reacts as expected. However, when I try to turn off two or more lights, Google immediately responds that the 'plugin name' is not available. I can see in the log the JSON strings. I added the part of the log when calling for two devices.
[Log call two devices.txt](https://github.com/DewGew/DZGA-Flask/files/13452941/Log.call.two.devices.txt)

**Comment by DewGew** [comment]
No errors in the log?

**Comment by Xenomes** [comment]
No errors. Can I put the plugin in debug mode?

**Comment by DewGew** [comment]
I have that issue also. Trying to figure out how to fix this

**Comment by Xenomes** [comment]
Okay, that's good you can duplicate the problem.

**Comment by Xenomes** [comment]
Very nice! Multi devices is working now, still got the the message from google that 'plugin name' is not available when changing more devices.
