### ISSUE TITLE
Call to turn off a light that is already off notification.

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#61]
I don't know if it is a bug. With the Domoticz-Google-Assistant version, when I call to turn off a light that is already off, Google announces that the light has already been turned off. That is not happening in the Flask version.

**Comment by DewGew** [comment]
Its not yet implemented.

**Comment by Xenomes** [comment]
Okay, perfect!

**Comment by DewGew** [comment]
I made a PR with already in state message. There will be a possible to turn this off in device config.
