### ISSUE TITLE
Blinds are in reverse.

### ISSUE THREAD

**Issue by Xenomes** [DewGew/DZGA-Flask#64]
Hi,
When calling Google to close the blinds, the blinds go open. I do have the reverse position enabled in Domoticz to correct the open/close. The open/close in Domoticz works as expected, where open is 0%, and close is 100%.

![afbeelding](https://github.com/DewGew/DZGA-Flask/assets/11648297/cc59ab29-5c05-4070-8f6f-819b9091a922)

**Comment by DewGew** [comment]
Google wants blinds reported like: openPercent = 100 so open = 100% and closed = 0%

**Comment by Xenomes** [comment]
Okay, that is clear then 😅
