### ISSUE TITLE
Help wanted: Implement ngrok for a secure SSL tunnel with valid public HTTPS URL

### ISSUE THREAD

**Issue by Xavier82** [DewGew/DZGA-Flask#68]
In previous version of DZGA there was the option for NGROK with key, worked like a charm.
Is NGROK still needed (I don't use reverse proxy, nor do I have a own domain)?

The Wiki doesn't provide me sufficient information about this.

What has to be done to use NGROK?

I use the Smart-home-key.json file (same as DZGA), but I get a 401 error, probably because of NGROK?

**Comment by DewGew** [comment]
I dont implemnt ngrok for now. you can try running you self : https://www.tutorialspoint.com/how-to-run-python-flask-app-online-using-ngrok
