### ISSUE TITLE
Missing devices

### ISSUE THREAD

**Issue by Paul-Amsterdam** [DewGew/DZGA-Flask#72]
Thank you for making DZGA flask. 
Just like in the old version of DZGA, I don't see a number of devices in DZGA-flask even though they are in the room in question. It is a switch type: Lighting 4 SubType: SPT2262. Via controlicz it worked. Am I doing something wrong? 

This is a translation to English

**Comment by DewGew** [comment]
> Thank you for making DZGA flask. 
> 
> Just like in the old version of DZGA, I don't see a number of devices in DZGA-flask even though they are in the room in question. It is a switch type: Lighting 4 SubType: SPT2262. Via controlicz it worked. Am I doing something wrong? 
> 
> 
> 
> 
> 
> This is a translation to English

This device is now added

**Comment by Paul-Amsterdam** [comment]
Great, they're there. Thanks for the super quick fix.

**Comment by Paul-Amsterdam** [comment]
In dzga, all devices from the specified room are now listed. Unfortunately, I can't update it in Google home. I get the login page, but when I confirm it, I get the message that I can't reach it. The strange thing is that I could continue to control the devices that were already in Google home, but updating the added devices was not possible. After removing dzga, it is no longer possible to add it. What am I doing wrong?

**Comment by Paul-Amsterdam** [comment]
I have no idea what I did wrong but I did it all over again. Installed dzga-again and created a new action at Google. Google home did get them in, but they were offline. Forgot to set Homegraph to enable. Now everything is working again. I'm happy!
