### ISSUE TITLE
Could'nt reach mydzga

### ISSUE THREAD

**Issue by Paul-Amsterdam** [DewGew/DZGA-Flask#75]
Unfortunately, I run into a problem when installing it on my Raspberry pi5. Unfortunately I couldn't transfer the installation on the pi4. Now I was able to install Bookworm right away. Everything is running now but now I have the problem with Google home assistant to register the devices. When adding in the app, I can just log in securely to mydzga. Unfortunately, when syncing the devices, I get the message of Could'nt reach mydzga Try again. What did I do wrong?

**Comment by DewGew** [comment]
Can you reach UI from internet?

**Comment by Paul-Amsterdam** [comment]
Yes, I can reach mydzga (UI) via a secure connection over the internet. With the Google home app to link the devices, I log in with the secure connection. After that, I get the notification of linking etc. Shortly afterwards the message that he can't reach my mydzga.

**Comment by DewGew** [comment]
Is Google Assistant enabled in dzga UI?

**Comment by Paul-Amsterdam** [comment]
Yes, the Google Assistant is enabled (both) in dzga UI.
Also, synchronizing the devices with Domoticz is problematic. This morning I managed to synchronize it and thought that's nice. In Domoticz, devices were added to the same room, but they are no longer synchronized. 
The whole thing runs on a raspberry 5 with Bookworm.
Thanks for your help. 

Translated with Google

**Comment by Xavier82** [comment]
Same issue here Paul-Amsterdam, I can't get my [test] DZGA project connected within Google Home.
Connection to Domoticz works fine. Aslong as I can't pair Google Home to my [test] DZGA project I can't sync from DZGA to Google Home and I get the 404 error.

I have created an incident @Google SmartHome team to investigate this. ( I use Ngrok btw)

**Comment by Paul-Amsterdam** [comment]
I use Nginx.

**Comment by Xavier82** [comment]
I know, but I wanted to designate that there is no difference between Nginx and/or Ngrok.
Both don't work.....

**Comment by Paul-Amsterdam** [comment]
> Same issue here Paul-Amsterdam, I can't get my [test] DZGA project connected within Google Home. Connection to Domoticz works fine. Aslong as I can't pair Google Home to my [test] DZGA project I can't sync from DZGA to Google Home and I get the 404 error.
> 
> I have created an incident @google SmartHome team to investigate this. ( I use Ngrok btw)

The weird thing is that I had it work on a Raspberry Pi 4. But even now it doesn't work anymore. Curious to see if your request to Google yields anything. 
Please let us know.

Translated with Google.

**Comment by Xavier82** [comment]
I got a response from google about this issue.
It seems to be an issue with the sync. I use in Domoticz a device "Door lock Inverted" to monitor my garagedoor.
In Domoticz this is set as a type "Light", Google knows 2 action types "On" or "Off" while Domoticz status "Locked" or "Unlocked".

This is a copy of the reaction of Google support:
`Dear Developer,

Thank you for sharing the information with us. We've identified an issue with your SYNC Response. The device with device_id DoorLockInverted_353 is marked as a LIGHT type, but its traits are empty, which is invalid. For LIGHT types, the OnOff traits are required. Please refer to https://developers.home.google.com/cloud-to-cloud/guides/light.

To resolve this, kindly update your SYNC Response and ensure it's valid. You can use the [SYNC Data Validator]([](https://developers.home.google.com/tools/sync-data-validator?hl=en)) for validation.`

I also checked [https://developers.home.google.com/cloud-to-cloud/guides/lock](url)

Is this something which can be fixed in DZGA-Flask? Since I can't choose a device type in Domoticz because type "Light" is fixed to Door Lock (Inverted) in Domoticz.

@Paul-Amsterdam: Do you also have door locks in your setup?

@DewGew: Is there a possibility to check the devices first in the Google Validator en when there are issues they show up in the logging? Or maybe create a .json outputfile which can be used in the validator?

**Comment by Xavier82** [comment]
As per test I have disabled all devices which have/are "Doorlock" in Domoticz.
I restarted DZGA and I did a sync between DZGA and Domoticz.
I went to Google Home and I added again the service "[test] DZGA", and now indeed I'm able to connect to Google Home.
So I think we have tracked a possible issue with these type of devices.....

I think this issue is the same problem or part of it and also reflects to DZGA-Flask:
[https://github.com/DewGew/Domoticz-Google-Assistant/issues/351](url)

**Comment by DewGew** [comment]
Unsupported device can you see under "other devices" in UI dashboard. So if you exclude that device, (set as hide in device config) it should work.

**Comment by Paul-Amsterdam** [comment]
I don't use door locks. Thanks for the effort Xavier82 made with Google. 
I can now add some devices to get it into Google home. Previous devices that I got in the old dzga for Google home don't work now. Linking to Google home now indicates that it cannot be reached. In other words, the old story.
I'm glad I have some of them in Google home now, I hope the rest can be added soon. 

DewGew: Hidden devices still gives the error with can't reach etc. Only if I Remove from the room, the reconnection is going well. 

Translated with Google.

**Comment by DewGew** [comment]
> I don't use door locks. Thanks for the effort Xavier82 made with Google. I can now add some devices to get it into Google home. Previous devices that I got in the old dzga for Google home don't work now. Linking to Google home now indicates that it cannot be reached. In other words, the old story. I'm glad I have some of them in Google home now, I hope the rest can be added soon.
> 
> DewGew: Hidden devices still gives the error with can't reach etc. Only if I Remove from the room, the reconnection is going well.
> 
> Translated with Google.

Wich devices don't work except?

**Comment by DewGew** [comment]
BTW I have added DoorLockInverted in latest

**Comment by Paul-Amsterdam** [comment]
> Wich devices don't work except?

3 where I am sure of:
189	RFXcom	5A8FE1	0	op	 Lighting	4	PT2262	On
188	RFXcom	5A8FE2	0	Stop	 Lighting	4	PT2262	On
190	RFXcom	5A8FE4	0	Neer  Lighting	4	PT2262	On

Not Translated with Google. :-)

**Comment by DewGew** [comment]
Lighting 4 should be worki
Can you share json output for one of those devices? 
Log in to domoticz then  enter in a browser http://xxx.xxx.x.xx:8080/json.htm?type=command&param=getdevices&rid=IDX

**Comment by Paul-Amsterdam** [comment]
I tested it again to be sure. It syncs with dzga-flask but not with Google home.

I used this line in the browser: <http://192.168.178.55:8088/json.htm?type=command&param=getdevices&rid=188> &param=getdevices&rid=188 and that gave the json in the browser. I have added this as an attachment.

Good luck en thank you.

 

Van: DewGew ***@***.***> 
Verzonden: maandag 29 januari 2024 17:47
Aan: DewGew/DZGA-Flask ***@***.***>
CC: Paul-Amsterdam ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [DewGew/DZGA-Flask] Could'nt reach mydzga (Issue #75)

 

Lighting 4 should be worki
Can you share json output for one of those devices?
Log in to domoticz the enter in a browser http://xxx.xxx.x.xx:8080/json.htm?type=command <http://xxx.xxx.x.xx:8080/json.htm?type=command&param=getdevices&rid=IDX> &param=getdevices&rid=IDX

**Comment by Paul-Amsterdam** [comment]
the json from the device:

"ActTime" : 1706601237,
	"AstrTwilightEnd" : "19:20",
	"AstrTwilightStart" : "06:27",
	"CivTwilightEnd" : "17:59",
	"CivTwilightStart" : "07:48",
	"DayLength" : "08:57",
	"NautTwilightEnd" : "18:40",
	"NautTwilightStart" : "07:07",
	"ServerTime" : "2024-01-30 08:53:57",
	"SunAtSouth" : "12:54",
	"Sunrise" : "08:25",
	"Sunset" : "17:22",
	"app_version" : "2024.3",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "On",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 3,
			"HardwareName" : "RFXcom",
			"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
			"HardwareTypeVal" : 1,
			"HaveDimmer" : false,
			"HaveGroupCmd" : false,
			"HaveTimeout" : false,
			"ID" : "5A8FE2",
			"Image" : "Push",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-01-29 22:34:56",
			"Level" : 0,
			"LevelInt" : 433,
			"MaxDimLevel" : 0,
			"Name" : "Stop",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "PT2262",
			"SwitchType" : "Push Off Button",
			"SwitchTypeVal" : 10,
			"Timers" : "false",
			"Type" : "Lighting 4",
			"TypeImg" : "pushoff",
			"Unit" : 0,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "188"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

**Comment by DewGew** [comment]
> the json from the device:
> 
> "ActTime" : 1706601237, "AstrTwilightEnd" : "19:20", "AstrTwilightStart" : "06:27", "CivTwilightEnd" : "17:59", "CivTwilightStart" : "07:48", "DayLength" : "08:57", "NautTwilightEnd" : "18:40", "NautTwilightStart" : "07:07", "ServerTime" : "2024-01-30 08:53:57", "SunAtSouth" : "12:54", "Sunrise" : "08:25", "Sunset" : "17:22", "app_version" : "2024.3", "result" : [ { "AddjMulti" : 1.0, "AddjMulti2" : 1.0, "AddjValue" : 0.0, "AddjValue2" : 0.0, "BatteryLevel" : 255, "CustomImage" : 0, "Data" : "On", "Description" : "", "DimmerType" : "none", "Favorite" : 1, "HardwareDisabled" : false, "HardwareID" : 3, "HardwareName" : "RFXcom", "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver", "HardwareTypeVal" : 1, "HaveDimmer" : false, "HaveGroupCmd" : false, "HaveTimeout" : false, "ID" : "5A8FE2", "Image" : "Push", "IsSubDevice" : false, "LastUpdate" : "2024-01-29 22:34:56", "Level" : 0, "LevelInt" : 433, "MaxDimLevel" : 0, "Name" : "Stop", "Notifications" : "false", "PlanID" : "0", "PlanIDs" : [ 0 ], "Protected" : false, "ShowNotifications" : true, "SignalLevel" : "-", "Status" : "", "StrParam1" : "", "StrParam2" : "", "SubType" : "PT2262", "SwitchType" : "Push Off Button", "SwitchTypeVal" : 10, "Timers" : "false", "Type" : "Lighting 4", "TypeImg" : "pushoff", "Unit" : 0, "Used" : 1, "UsedByCamera" : false, "XOffset" : "0", "YOffset" : "0", "idx" : "188" } ], "status" : "OK", "title" : "Devices" }

I think this is fixed in from DZGA version 24.4

**Comment by Paul-Amsterdam** [comment]
Wow, that's awesome. It's unbelievable how quickly you've done that. Thank you very much for that.
