### ISSUE TITLE
Error: data.payload.devices[0].attributes.sceneReversible is required for Scenes

### ISSUE THREAD

**Issue by Xavier82** [DewGew/DZGA-Flask#79]
Using [https://developers.home.google.com/tools/sync-data-validator?hl=en](url) I have added the json and ran the validation.
I get this error back:
`data.payload.devices[0].attributes.sceneReversible is required for Scenes`

This should be the trait:
[https://developers.home.google.com/cloud-to-cloud/traits/scene](url)

Can you fix this?

**Comment by DewGew** [comment]
What is the problem?

**Comment by DewGew** [comment]
sceneReversible - Indicates that this scene can be cancelled. This attribute is only relevant for scenes that modify state and remember previous state.

I think that domoticz scene not can be cancelled (also no deactivate of scenes either)

**Comment by Xavier82** [comment]
> What is the problem?

Google Home gets this as an issue and therefor cannot connect.
When using the validator of Google it says it needs a value.
Indeed Domoticz scene can't be cancelled but If there are scenes in Domoticz, then Google Home just expects the value for it.

**Comment by DewGew** [comment]
Not needed sceneReversible is set to False be default. closing this issue
