### ISSUE TITLE
Synchronisation and doorbell notification issues

### ISSUE THREAD

**Issue by thijsniehof** [DewGew/DZGA-Flask#91]
Domoticz 2042.4
DZGA-Flask 24.6

Since a while, I don't receive the voice notification on my smart speakers anymore, when the doorbell button is pressed.
This used to work, but somewhere along the line this stopped (not sure at which Domoticz / DZGA update it stopped).
HTTP notification is setup properly in the settings, the notification for the doorbell switch is {"id":"Doorbell_409", "state": "$value"}

Also, "sync devices" from within the DZGA-flask GUI does not work anymore, it produces an error: "Error syncing devices with domoticz"
When I add or remove devices to the "Google home" in domoticz, they won't show up when trying to sync. If however I restart the DZGA-flask container, they do show up and work flawlessly.

I can turn on/off devices from the google home app and with voice commands, the status in the Google Home is also updated when the state of a switch is changed.

**Comment by DewGew** [comment]
Is smart-home-key.json in correct folder? I moved it to config folder

**Comment by thijsniehof** [comment]
That was the trick, at least for the sync issue..Cannot test the notifications right now, not at home.

**Comment by DewGew** [comment]
Notifications works in my setup.

**Comment by thijsniehof** [comment]
Finally time to test the voice notifications: they're also working again..
Thanks for the help, once again :)
