### ISSUE TITLE
room and nicknames are not saved after being entered in gui

### ISSUE THREAD

**Issue by vreesie18** [DewGew/DZGA-Flask#92]
I tried to enter room and nickname for my devices in the web gui but nothing is saved. 

Q2: what is the proper place in the json for the room attribute ? I am writing conversion software for my dzga config to flask config.

Many thanks in advance.

Regards,
Andre

**Comment by DewGew** [comment]
When you click save, it saves to the database, but you need to sync devices berfore it shows in the ui.(small bug)

**Comment by DewGew** [comment]
"roomHint": "kitchen" in json file

**Comment by vreesie18** [comment]
Where is the data like nicknames and rooms stored ? I wrote a script to convert my dzga config to flask config but I saw that my converted nicknames and rooms disappeared after a sync.

"OnOff_8653": {
        "id": "Tuin_Licht",
        "type": "action.devices.types.LIGHT",
        "traits": [
            "action.devices.traits.OnOff"
        ],
        "name": {
            "name": "Tuinlampen",
            "nicknames": [
                "Tuin Licht"
            ]
        },
        "willReportState": true,
        "attributes": [],
        "customData": {
            "dzTags": false,
            "idx": "8653",
            "domain": "OnOff",
            "protected": false
        },
        "notificationSupportedByAgent": false,
        "roomHint": "xxxyyyzzz1c"

**Comment by DewGew** [comment]
Its saved in a database `/instance/db.sqlite`

**Comment by vreesie18** [comment]
Check that works! Thanks!
