### ISSUE TITLE
Possibility to disable / enable voice match

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/DZGA-Flask#93]
It would be nice if there could be a function to switch Off an On my Google Devices for voice match.
When I go on holiday I would like to have my Google devices NOT to listen anymore to voice commands, and ofcourse to switch it on again when I am back from holiday.
I know I can do it on my phone, but just want to have an automated way of doing that.

**Comment by DewGew** [comment]
You can go into DZGA UI then disable Google Assistant.

EDIT:
I can create a api to this so you can you can use this in a script

**Comment by SargonofAssyria** [comment]
The API would be more then welcome, because I can then use my "Holiday" button in Domoticz, which I also use for other settings.

**Comment by DewGew** [comment]
https://github.com/DewGew/DZGA-Flask/wiki/5.-API
