### ISSUE TITLE
 issue with Philips Hue bulbs

### ISSUE THREAD

**Issue by vreesie18** [DewGew/DZGA-Flask#97]
I seems to be having an issue with Philips Hue bulbs.

They come as source from domoticz in flask, I see them in flask, I see them in my room in Google Home, I can change settings in the Google Home app but I can't talk to the assistant to have the lights turned on. 

All my other non Philips Hue devices work okay.

Am I missing something ?

    "ColorSwitch_2436": {
        "id": "ColorSwitch_2436",
        "type": "action.devices.types.LIGHT",
        "traits": [
            "action.devices.traits.OnOff",
            "action.devices.traits.Brightness",
            "action.devices.traits.ColorSetting"
        ],
        "name": {
            "name": "Dinner table",
            "nicknames": []
        },
        "willReportState": true,
        "attributes": {
            "colorModel": "rgb",
            "colorTemperatureRange": {
                "temperatureMinK": 1700,
                "temperatureMaxK": 6500
            }
        },
        "customData": {
            "dzTags": false,
            "idx": "2436",
            "domain": "ColorSwitch",
            "protected": false
        },
        "notificationSupportedByAgent": false

![Screenshot 2024-02-06 130427](https://github.com/DewGew/DZGA-Flask/assets/37900374/840b0688-7318-4fd9-a53c-bcbf6e40ecd3)

**Comment by DewGew** [comment]
can you turn it on off in UI? In Google Home app by clicking it?

**Comment by vreesie18** [comment]
It appeared to be a mistake on my part. I had created a script loop in Domoticz. Thanks for the support again anyhow!!!!
